spring:
#  datasource:
#    driver-class-name: org.h2.Driver
#    username: ${DB_ID}
#    password: ${DB_PASSWORD}
#    url: ${DB_URL}
  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  data:
    web:
      pageable:
        default-page-size: 20
server:
  port: 8089
logging.level:
  org.hibernate.SQL: debug

